minimumReleaseAge: 10080
engineStrict: true

overrides:
  vite-plugin-simple-json-server>vite: ^7.0.5
  # Below needed for svelte-headless-table
  svelte-headless-table>svelte: ^4.0.0 || ^5.0.0
  svelte-render>svelte: ^5.37.1
  svelte-subscribe>svelte: ^5.37.1
  svelte-keyed>svelte: ^5.37.1
  # Below needed for @reown/appkit - try removing once we upgrade
  abitype>zod: ^4.0.5
  '@reown/appkit-wallet>zod': ^4.0.5
