import { describe, expect, test } from 'vitest';
import {
	buildStablecoinChainHeatmapPayload,
	STABLECOIN_CHAIN_HEATMAP_OUTLIER_THRESHOLD,
	STABLECOIN_CHAIN_HEATMAP_TOP_N
} from './stablecoin-chain-heatmap';

function createVault(overrides: Record<string, unknown> = {}) {
	return {
		id: 'vault',
		name: 'Vault',
		vault_slug: 'vault',
		protocol_slug: 'protocol',
		lifetime_return: null,
		lifetime_return_net: null,
		cagr: null,
		cagr_net: null,
		three_months_returns: null,
		three_months_returns_net: null,
		three_months_cagr: null,
		three_months_cagr_net: null,
		three_months_sharpe: null,
		three_months_sharpe_net: null,
		three_months_volatility: null,
		one_month_returns: null,
		one_month_returns_net: null,
		one_month_cagr: null,
		one_month_cagr_net: null,
		denomination: 'USDC',
		normalised_denomination: 'USD Coin',
		denomination_slug: 'usdc',
		share_token: 'A',
		chain: 'Ethereum',
		peak_nav: 120,
		current_nav: 100,
		years: null,
		mgmt_fee: null,
		perf_fee: null,
		deposit_fee: null,
		withdraw_fee: null,
		fee_mode: null,
		fee_internalised: null,
		gross_fees: null,
		net_fees: null,
		lockup: null,
		event_count: null,
		protocol: 'Aave',
		risk: 'Low',
		risk_numeric: 20,
		start_date: '2025-01-01T00:00:00',
		end_date: '2026-01-01T00:00:00',
		address: '0x1111111111111111111111111111111111111111',
		share_token_address: null,
		denomination_token_address: null,
		chain_id: 1,
		stablecoinish: true,
		first_updated_at: null,
		first_updated_block: null,
		last_updated_at: '2026-01-01T00:00:00',
		last_updated_block: 1,
		last_share_price: null,
		features: [],
		flags: [],
		notes: null,
		deposit_closed_reason: null,
		redemption_closed_reason: null,
		deposit_next_open: null,
		redemption_next_open: null,
		link: null,
		trading_strategy_link: null,
		fee_label: null,
		deposit_ui_link: null,
		vault_page_link: null,
		share_token_link: null,
		deposit_manager_link: null,
		badges: [],
		period_results: [],
		...overrides
	} as any;
}

describe('buildStablecoinChainHeatmapPayload', () => {
	test('groups current TVL by stablecoin and display chain while excluding blacklisted and outlier vaults', () => {
		const payload = buildStablecoinChainHeatmapPayload(
			[
				{
					id: 'usdc-eth-a',
					name: 'USDC Ethereum A',
					vault_slug: 'usdc-ethereum-a',
					protocol_slug: 'aave',
					lifetime_return: null,
					lifetime_return_net: null,
					cagr: null,
					cagr_net: null,
					three_months_returns: null,
					three_months_returns_net: null,
					three_months_cagr: null,
					three_months_cagr_net: null,
					three_months_sharpe: null,
					three_months_sharpe_net: null,
					three_months_volatility: null,
					one_month_returns: null,
					one_month_returns_net: null,
					one_month_cagr: null,
					one_month_cagr_net: null,
					denomination: 'USDC',
					normalised_denomination: 'USD Coin',
					denomination_slug: 'usdc',
					share_token: 'A',
					chain: 'Ethereum',
					peak_nav: 120,
					current_nav: 100,
					years: null,
					mgmt_fee: null,
					perf_fee: null,
					deposit_fee: null,
					withdraw_fee: null,
					fee_mode: null,
					fee_internalised: null,
					gross_fees: null,
					net_fees: null,
					lockup: null,
					event_count: null,
					protocol: 'Aave',
					risk: 'Low',
					risk_numeric: 20,
					start_date: '2025-01-01T00:00:00',
					end_date: '2026-01-01T00:00:00',
					address: '0x1111111111111111111111111111111111111111',
					share_token_address: null,
					denomination_token_address: null,
					chain_id: 1,
					stablecoinish: true,
					first_updated_at: null,
					first_updated_block: null,
					last_updated_at: '2026-01-01T00:00:00',
					last_updated_block: 1,
					last_share_price: null,
					features: [],
					flags: [],
					notes: null,
					deposit_closed_reason: null,
					redemption_closed_reason: null,
					deposit_next_open: null,
					redemption_next_open: null,
					link: null,
					trading_strategy_link: null,
					fee_label: null,
					deposit_ui_link: null,
					vault_page_link: null,
					share_token_link: null,
					deposit_manager_link: null,
					badges: [],
					period_results: []
				},
				{
					id: 'usdc-hyper',
					name: 'USDC Hyperliquid',
					vault_slug: 'usdc-hyper',
					protocol_slug: 'yearn',
					lifetime_return: null,
					lifetime_return_net: null,
					cagr: null,
					cagr_net: null,
					three_months_returns: null,
					three_months_returns_net: null,
					three_months_cagr: null,
					three_months_cagr_net: null,
					three_months_sharpe: null,
					three_months_sharpe_net: null,
					three_months_volatility: null,
					one_month_returns: null,
					one_month_returns_net: null,
					one_month_cagr: null,
					one_month_cagr_net: null,
					denomination: 'USDC',
					normalised_denomination: 'USD Coin',
					denomination_slug: 'usdc',
					share_token: 'B',
					chain: 'Hyperliquid',
					peak_nav: 260,
					current_nav: 250,
					years: null,
					mgmt_fee: null,
					perf_fee: null,
					deposit_fee: null,
					withdraw_fee: null,
					fee_mode: null,
					fee_internalised: null,
					gross_fees: null,
					net_fees: null,
					lockup: null,
					event_count: null,
					protocol: 'Yearn',
					risk: 'Low',
					risk_numeric: 20,
					start_date: '2025-01-01T00:00:00',
					end_date: '2026-01-01T00:00:00',
					address: '0x2222222222222222222222222222222222222222',
					share_token_address: null,
					denomination_token_address: null,
					chain_id: 9999,
					stablecoinish: true,
					first_updated_at: null,
					first_updated_block: null,
					last_updated_at: '2026-01-01T00:00:00',
					last_updated_block: 1,
					last_share_price: null,
					features: [],
					flags: [],
					notes: null,
					deposit_closed_reason: null,
					redemption_closed_reason: null,
					deposit_next_open: null,
					redemption_next_open: null,
					link: null,
					trading_strategy_link: null,
					fee_label: null,
					deposit_ui_link: null,
					vault_page_link: null,
					share_token_link: null,
					deposit_manager_link: null,
					badges: [],
					period_results: []
				},
				{
					id: 'dai-base',
					name: 'DAI Base',
					vault_slug: 'dai-base',
					protocol_slug: 'maker',
					lifetime_return: null,
					lifetime_return_net: null,
					cagr: null,
					cagr_net: null,
					three_months_returns: null,
					three_months_returns_net: null,
					three_months_cagr: null,
					three_months_cagr_net: null,
					three_months_sharpe: null,
					three_months_sharpe_net: null,
					three_months_volatility: null,
					one_month_returns: null,
					one_month_returns_net: null,
					one_month_cagr: null,
					one_month_cagr_net: null,
					denomination: 'DAI',
					normalised_denomination: 'Dai',
					denomination_slug: 'dai',
					share_token: 'C',
					chain: 'Base',
					peak_nav: 81,
					current_nav: 80,
					years: null,
					mgmt_fee: null,
					perf_fee: null,
					deposit_fee: null,
					withdraw_fee: null,
					fee_mode: null,
					fee_internalised: null,
					gross_fees: null,
					net_fees: null,
					lockup: null,
					event_count: null,
					protocol: 'Maker',
					risk: 'Low',
					risk_numeric: 20,
					start_date: '2025-01-01T00:00:00',
					end_date: '2026-01-01T00:00:00',
					address: '0x3333333333333333333333333333333333333333',
					share_token_address: null,
					denomination_token_address: null,
					chain_id: 8453,
					stablecoinish: true,
					first_updated_at: null,
					first_updated_block: null,
					last_updated_at: '2026-01-01T00:00:00',
					last_updated_block: 1,
					last_share_price: null,
					features: [],
					flags: [],
					notes: null,
					deposit_closed_reason: null,
					redemption_closed_reason: null,
					deposit_next_open: null,
					redemption_next_open: null,
					link: null,
					trading_strategy_link: null,
					fee_label: null,
					deposit_ui_link: null,
					vault_page_link: null,
					share_token_link: null,
					deposit_manager_link: null,
					badges: [],
					period_results: []
				},
				{
					id: 'blacklisted',
					name: 'Blacklisted',
					vault_slug: 'blacklisted',
					protocol_slug: 'bad',
					lifetime_return: null,
					lifetime_return_net: null,
					cagr: null,
					cagr_net: null,
					three_months_returns: null,
					three_months_returns_net: null,
					three_months_cagr: null,
					three_months_cagr_net: null,
					three_months_sharpe: null,
					three_months_sharpe_net: null,
					three_months_volatility: null,
					one_month_returns: null,
					one_month_returns_net: null,
					one_month_cagr: null,
					one_month_cagr_net: null,
					denomination: 'USDT',
					normalised_denomination: 'Tether',
					denomination_slug: 'usdt',
					share_token: 'D',
					chain: 'Ethereum',
					peak_nav: 1000,
					current_nav: 999,
					years: null,
					mgmt_fee: null,
					perf_fee: null,
					deposit_fee: null,
					withdraw_fee: null,
					fee_mode: null,
					fee_internalised: null,
					gross_fees: null,
					net_fees: null,
					lockup: null,
					event_count: null,
					protocol: 'Bad',
					risk: 'Blacklisted',
					risk_numeric: 999,
					start_date: '2025-01-01T00:00:00',
					end_date: '2026-01-01T00:00:00',
					address: '0x4444444444444444444444444444444444444444',
					share_token_address: null,
					denomination_token_address: null,
					chain_id: 1,
					stablecoinish: true,
					first_updated_at: null,
					first_updated_block: null,
					last_updated_at: '2026-01-01T00:00:00',
					last_updated_block: 1,
					last_share_price: null,
					features: [],
					flags: [],
					notes: null,
					deposit_closed_reason: null,
					redemption_closed_reason: null,
					deposit_next_open: null,
					redemption_next_open: null,
					link: null,
					trading_strategy_link: null,
					fee_label: null,
					deposit_ui_link: null,
					vault_page_link: null,
					share_token_link: null,
					deposit_manager_link: null,
					badges: [],
					period_results: []
				},
				{
					id: 'outlier',
					name: 'Outlier',
					vault_slug: 'outlier',
					protocol_slug: 'bad',
					lifetime_return: null,
					lifetime_return_net: null,
					cagr: null,
					cagr_net: null,
					three_months_returns: null,
					three_months_returns_net: null,
					three_months_cagr: null,
					three_months_cagr_net: null,
					three_months_sharpe: null,
					three_months_sharpe_net: null,
					three_months_volatility: null,
					one_month_returns: null,
					one_month_returns_net: null,
					one_month_cagr: null,
					one_month_cagr_net: null,
					denomination: 'USDT',
					normalised_denomination: 'Tether',
					denomination_slug: 'usdt',
					share_token: 'E',
					chain: 'Base',
					peak_nav: STABLECOIN_CHAIN_HEATMAP_OUTLIER_THRESHOLD + 10,
					current_nav: STABLECOIN_CHAIN_HEATMAP_OUTLIER_THRESHOLD + 1,
					years: null,
					mgmt_fee: null,
					perf_fee: null,
					deposit_fee: null,
					withdraw_fee: null,
					fee_mode: null,
					fee_internalised: null,
					gross_fees: null,
					net_fees: null,
					lockup: null,
					event_count: null,
					protocol: 'Bad',
					risk: 'Low',
					risk_numeric: 20,
					start_date: '2025-01-01T00:00:00',
					end_date: '2026-01-01T00:00:00',
					address: '0x5555555555555555555555555555555555555555',
					share_token_address: null,
					denomination_token_address: null,
					chain_id: 8453,
					stablecoinish: true,
					first_updated_at: null,
					first_updated_block: null,
					last_updated_at: '2026-01-01T00:00:00',
					last_updated_block: 1,
					last_share_price: null,
					features: [],
					flags: [],
					notes: null,
					deposit_closed_reason: null,
					redemption_closed_reason: null,
					deposit_next_open: null,
					redemption_next_open: null,
					link: null,
					trading_strategy_link: null,
					fee_label: null,
					deposit_ui_link: null,
					vault_page_link: null,
					share_token_link: null,
					deposit_manager_link: null,
					badges: [],
					period_results: []
				}
			] as any,
			[],
			145.4,
			new Date('2026-03-21T12:00:00Z'),
			{ minTvl: 0 }
		);

		expect(payload.generatedAt).toBe('2026-03-21T12:00:00.000Z');
		expect(payload.durationMs).toBe(145);
		expect(payload.chains).toEqual([
			expect.objectContaining({
				key: 'hyperliquid',
				label: 'Hyperliquid',
				totalTvl: 250,
				chainIds: [9999],
				href: '/trading-view/vaults/chains/hyperliquid',
				logoUrl: '/logos/blockchains/hyperliquid'
			}),
			expect.objectContaining({
				key: 'ethereum',
				label: 'Ethereum',
				totalTvl: 100,
				chainIds: [1],
				href: '/trading-view/vaults/chains/ethereum',
				logoUrl: '/logos/blockchains/ethereum'
			}),
			expect.objectContaining({
				key: 'base',
				label: 'Base',
				totalTvl: 80,
				chainIds: [8453],
				href: '/trading-view/vaults/chains/base',
				logoUrl: '/logos/blockchains/base'
			})
		]);
		expect(payload.stablecoins).toEqual([
			expect.objectContaining({
				key: 'usdc',
				label: 'USDC',
				totalTvl: 350,
				stablecoinSlug: 'usdc',
				href: '/trading-view/vaults/stablecoins/usdc'
			}),
			expect.objectContaining({
				key: 'dai',
				label: 'DAI',
				totalTvl: 80,
				stablecoinSlug: 'dai',
				href: '/trading-view/vaults/stablecoins/dai'
			})
		]);
		expect(payload.cells).toEqual([
			expect.objectContaining({
				chainKey: 'hyperliquid',
				stablecoinKey: 'usdc',
				tvl: 250,
				vaultCount: 1,
				apy: null,
				monthlyReturn: null
			}),
			expect.objectContaining({
				chainKey: 'ethereum',
				stablecoinKey: 'usdc',
				tvl: 100,
				vaultCount: 1,
				apy: null,
				monthlyReturn: null
			}),
			expect.objectContaining({
				chainKey: 'base',
				stablecoinKey: 'dai',
				tvl: 80,
				vaultCount: 1,
				apy: null,
				monthlyReturn: null
			})
		]);
		expect(payload.meta).toEqual({
			includedVaults: 3,
			excludedBlacklistedVaults: 1,
			excludedOutlierVaults: 1,
			nonZeroCells: 3
		});
	});

	test('limits the heatmap axes to the top TVL stablecoins and chains', () => {
		const vaults = Array.from({ length: STABLECOIN_CHAIN_HEATMAP_TOP_N + 2 }, (_, index) => {
			const rank = index + 1;
			const tvl = (STABLECOIN_CHAIN_HEATMAP_TOP_N + 3 - rank) * 100;

			return {
				id: `vault-${rank}`,
				name: `Vault ${rank}`,
				vault_slug: `vault-${rank}`,
				protocol_slug: `protocol-${rank}`,
				lifetime_return: null,
				lifetime_return_net: null,
				cagr: null,
				cagr_net: null,
				three_months_returns: null,
				three_months_returns_net: null,
				three_months_cagr: null,
				three_months_cagr_net: null,
				three_months_sharpe: null,
				three_months_sharpe_net: null,
				three_months_volatility: null,
				one_month_returns: null,
				one_month_returns_net: null,
				one_month_cagr: null,
				one_month_cagr_net: null,
				denomination: `SC${rank}`,
				normalised_denomination: `Stablecoin ${rank}`,
				denomination_slug: `stablecoin-${rank}`,
				share_token: `S${rank}`,
				chain: `Chain ${rank}`,
				peak_nav: tvl,
				current_nav: tvl,
				years: null,
				mgmt_fee: null,
				perf_fee: null,
				deposit_fee: null,
				withdraw_fee: null,
				fee_mode: null,
				fee_internalised: null,
				gross_fees: null,
				net_fees: null,
				lockup: null,
				event_count: null,
				protocol: `Protocol ${rank}`,
				risk: 'Low',
				risk_numeric: 20,
				start_date: '2025-01-01T00:00:00',
				end_date: '2026-01-01T00:00:00',
				address: `0x${String(rank).padStart(40, '0')}`,
				share_token_address: null,
				denomination_token_address: null,
				chain_id: 50_000 + rank,
				stablecoinish: true,
				first_updated_at: null,
				first_updated_block: null,
				last_updated_at: '2026-01-01T00:00:00',
				last_updated_block: rank,
				last_share_price: null,
				features: [],
				flags: [],
				notes: null,
				deposit_closed_reason: null,
				redemption_closed_reason: null,
				deposit_next_open: null,
				redemption_next_open: null,
				link: null,
				trading_strategy_link: null,
				fee_label: null,
				deposit_ui_link: null,
				vault_page_link: null,
				share_token_link: null,
				deposit_manager_link: null,
				badges: [],
				period_results: []
			};
		});

		const payload = buildStablecoinChainHeatmapPayload(vaults as any, [], 87.3, new Date('2026-03-21T12:00:00Z'), {
			minTvl: 0
		});

		expect(payload.chains).toHaveLength(STABLECOIN_CHAIN_HEATMAP_TOP_N);
		expect(payload.stablecoins).toHaveLength(STABLECOIN_CHAIN_HEATMAP_TOP_N);
		expect(payload.cells).toHaveLength(STABLECOIN_CHAIN_HEATMAP_TOP_N);
		expect(payload.chains.map((chain) => chain.key)).not.toContain('chain-50011');
		expect(payload.chains.map((chain) => chain.key)).not.toContain('chain-50012');
		expect(payload.stablecoins.map((stablecoin) => stablecoin.key)).not.toContain('stablecoin-11');
		expect(payload.stablecoins.map((stablecoin) => stablecoin.key)).not.toContain('stablecoin-12');
		expect(payload.cells.every((cell) => cell.chainKey !== 'chain-50011' && cell.chainKey !== 'chain-50012')).toBe(
			true
		);
		expect(
			payload.cells.every((cell) => cell.stablecoinKey !== 'stablecoin-11' && cell.stablecoinKey !== 'stablecoin-12')
		).toBe(true);
	});

	test('calculates TVL-weighted APY and monthly return for each visible cell', () => {
		const payload = buildStablecoinChainHeatmapPayload(
			[
				createVault({
					id: 'eth-usdc-1',
					current_nav: 100,
					one_month_cagr_net: 0.1,
					one_month_returns_net: 0.02
				}),
				createVault({
					id: 'eth-usdc-2',
					address: '0x2222222222222222222222222222222222222222',
					current_nav: 300,
					one_month_cagr_net: 0.2,
					one_month_returns_net: 0.06
				})
			],
			[],
			12.6,
			new Date('2026-03-21T12:00:00Z'),
			{ minTvl: 0 }
		);

		expect(payload.cells).toEqual([
			expect.objectContaining({
				chainKey: 'ethereum',
				stablecoinKey: 'usdc',
				tvl: 400,
				vaultCount: 2,
				apy: 0.175,
				monthlyReturn: 0.05
			})
		]);
	});
});
