<!--
@component
Autogenerated "about" box for chain vault listing pages, mirroring the
protocol/curator description boxes. Summarises vault count, total TVL,
protocol count, the largest vaults, the most popular protocols and the
TVL-weighted 30-day average yield from the loaded vault data.

@example

```svelte
	<ChainDescription chainName="Base" vaults={topVaults.vaults} />
```
-->
<script lang="ts">
	import { resolve } from '$app/paths';
	import type { VaultInfo } from '$lib/top-vaults/schemas';
	import MetricsBox from '$lib/components/MetricsBox.svelte';
	import {
		calculateTotalTvl,
		calculateTvlWeightedApy,
		hasSupportedProtocol,
		isBlacklisted,
		isEligibleVaultGroupMiniChartVault,
		resolveVaultDetails
	} from '$lib/top-vaults/helpers';
	import { formatDollar, formatPercent } from '$lib/helpers/formatters';
	import { VAULT_TVL_OUTLIER_THRESHOLD } from '$lib/echarts/tvl-outliers';

	interface Props {
		chainName: string;
		vaults: VaultInfo[];
	}

	let { chainName, vaults }: Props = $props();

	// all headline stats derive from this set: exclude blacklisted vaults and broken
	// TVL outliers so a single bad data point doesn't inflate the figures
	let statsVaults = $derived(
		vaults.filter((v) => !isBlacklisted(v) && (v.current_nav ?? 0) <= VAULT_TVL_OUTLIER_THRESHOLD)
	);

	let totalTvl = $derived(calculateTotalTvl(statsVaults));
	let protocolCount = $derived(new Set(statsVaults.filter(hasSupportedProtocol).map((v) => v.protocol_slug)).size);
	let largestVaults = $derived(statsVaults.toSorted((a, b) => (b.current_nav ?? 0) - (a.current_nav ?? 0)).slice(0, 3));
	let topProtocols = $derived.by(() => {
		const tvlByProtocol = new Map<string, { slug: string; name: string; tvl: number }>();
		for (const vault of statsVaults) {
			if (!hasSupportedProtocol(vault)) continue;
			const entry = tvlByProtocol.get(vault.protocol_slug) ?? {
				slug: vault.protocol_slug,
				name: vault.protocol,
				tvl: 0
			};
			entry.tvl += vault.current_nav ?? 0;
			tvlByProtocol.set(vault.protocol_slug, entry);
		}
		return [...tvlByProtocol.values()].toSorted((a, b) => b.tvl - a.tvl).slice(0, 3);
	});
	// same eligible-vault set as the mini chart and the table's default filters,
	// so the yield agrees with the stats row below; filtered from statsVaults so
	// the TVL outlier guard applies here too
	let eligibleVaults = $derived(statsVaults.filter(isEligibleVaultGroupMiniChartVault));
	let averageYield = $derived(calculateTvlWeightedApy(eligibleVaults));
	// relative to the statsVaults count shown in the copy, so the two paragraphs
	// stay arithmetically consistent (shown count − excluded = listed vaults)
	let excludedVaultCount = $derived(statsVaults.length - eligibleVaults.length);
</script>

<div class="chain-description">
	<MetricsBox title="About {chainName} vaults">
		<p>
			{chainName} blockchain has {statsVaults.length} stablecoin vaults with {formatDollar(totalTvl, 1)} TVL across {protocolCount}
			protocols.
			{#if largestVaults.length}
				The largest vaults are
				{#each largestVaults as vault, index (vault.vault_slug)}{index > 0 ? ', ' : ''}<a
						href={resolveVaultDetails(vault)}>{vault.name}</a
					>{/each}
				{#if topProtocols.length}
					and the most popular vault protocols are
					{#each topProtocols as protocol, index (protocol.slug)}{index === 0
							? ''
							: index === topProtocols.length - 1
								? ' and '
								: ', '}<a href={resolve(`/trading-view/vaults/protocols/${protocol.slug}`)}>{protocol.name}</a
						>{/each}{/if}.
			{/if}
			{#if averageYield != null}
				The last 30 days' average yield is {formatPercent(averageYield, 1)}.
			{/if}
		</p>
		{#if excludedVaultCount > 0}
			<p>
				{excludedVaultCount} vaults are excluded from this ranking due to minimum TVL requirements or risk issues.
			</p>
		{/if}
	</MetricsBox>
</div>

<style>
	.chain-description {
		display: contents;
		font: var(--f-ui-md-roman);
		color: var(--c-text-light);

		p {
			margin: 0;
			line-height: 1.5;

			& + p {
				margin-top: 0.75rem;
			}
		}

		a {
			color: var(--c-text);
			text-decoration: underline;
			text-underline-offset: 0.2em;
		}
	}
</style>
