<!--
@component
Autogenerated "about" box for vault group listing pages (chains, stablecoins).
Summarises vault count, total TVL, protocol count, the largest vaults, the
most popular protocols, the TVL-weighted 30-day average yield and the
excluded vault count from the loaded vault data.

@example

```svelte
	<VaultGroupDescription title="About Base vaults" subject="Base blockchain" vaults={topVaults.vaults} />
```
-->
<script lang="ts">
	import { resolve } from '$app/paths';
	import type { VaultInfo } from '$lib/top-vaults/schemas';
	import MetricsBox from '$lib/components/MetricsBox.svelte';
	import {
		calculateTotalTvl,
		calculateTvlWeightedApy,
		hasSupportedProtocol,
		isBlacklisted,
		isEligibleVaultGroupMiniChartVault,
		getProtocolDisplayName,
		resolveVaultDetails
	} from '$lib/top-vaults/helpers';
	import { formatDollar, formatPercent } from '$lib/helpers/formatters';
	import { VAULT_TVL_OUTLIER_THRESHOLD } from '$lib/echarts/tvl-outliers';

	interface Props {
		/** MetricsBox heading, e.g. "About Base vaults" */
		title: string;
		/** Optional introductory sentence shown before the generated vault summary. */
		description?: string;
		/** Sentence opener naming the group, e.g. "Base blockchain" or "Circle USDC" */
		subject: string;
		/** Verb phrase linking the subject to the vault count, e.g. "has" or "is used in" */
		verbPhrase?: string;
		vaults: VaultInfo[];
	}

	let { title, description, subject, verbPhrase = 'has', vaults }: Props = $props();

	// all headline stats derive from this set: exclude blacklisted vaults and broken
	// TVL outliers so a single bad data point doesn't inflate the figures
	let statsVaults = $derived(
		vaults.filter((v) => !isBlacklisted(v) && (v.current_nav ?? 0) <= VAULT_TVL_OUTLIER_THRESHOLD)
	);

	let totalTvl = $derived(calculateTotalTvl(statsVaults));
	let protocolCount = $derived(new Set(statsVaults.filter(hasSupportedProtocol).map((v) => v.protocol_slug)).size);
	// dedupe by name so the same fund deployed on multiple chains isn't repeated
	let largestVaults = $derived.by(() => {
		const seen = new Set<string>();
		const result: VaultInfo[] = [];
		for (const vault of statsVaults.toSorted((a, b) => (b.current_nav ?? 0) - (a.current_nav ?? 0))) {
			if (seen.has(vault.name)) continue;
			seen.add(vault.name);
			result.push(vault);
			if (result.length === 3) break;
		}
		return result;
	});
	let topProtocols = $derived.by(() => {
		const tvlByProtocol = new Map<string, { slug: string; name: string; tvl: number }>();
		for (const vault of statsVaults) {
			if (!hasSupportedProtocol(vault)) continue;
			const entry = tvlByProtocol.get(vault.protocol_slug) ?? {
				slug: vault.protocol_slug,
				name: getProtocolDisplayName(vault.protocol, vault.protocol_slug),
				tvl: 0
			};
			entry.tvl += vault.current_nav ?? 0;
			tvlByProtocol.set(vault.protocol_slug, entry);
		}
		return [...tvlByProtocol.values()].toSorted((a, b) => b.tvl - a.tvl).slice(0, 3);
	});
	// same eligible-vault set as the mini chart and the table's default filters,
	// so the yield agrees with the stats row below; filtered from statsVaults so
	// the TVL outlier guard applies here too
	let eligibleVaults = $derived(statsVaults.filter(isEligibleVaultGroupMiniChartVault));
	let averageYield = $derived(calculateTvlWeightedApy(eligibleVaults));
	let vaultCountLabel = $derived(`${statsVaults.length} stablecoin ${statsVaults.length === 1 ? 'vault' : 'vaults'}`);
	let totalTvlLabel = $derived(`${formatDollar(totalTvl, 1)} TVL`);
	let protocolCountLabel = $derived(`${protocolCount} ${protocolCount === 1 ? 'protocol' : 'protocols'}`);
	let averageYieldLabel = $derived(averageYield == null ? null : formatPercent(averageYield, 1));
	// relative to the statsVaults count shown in the copy, so the two paragraphs
	// stay arithmetically consistent (shown count − excluded = listed vaults)
	let excludedVaultCount = $derived(statsVaults.length - eligibleVaults.length);
</script>

<div class="vault-group-description">
	<MetricsBox {title}>
		{#if description}
			<p>{description}</p>
		{/if}
		<p>
			{subject}
			{verbPhrase}
			<strong>{vaultCountLabel}</strong> with
			<strong>{totalTvlLabel}</strong>{#if protocolCount > 0}
				{' '}
				across <strong>{protocolCountLabel}</strong>{/if}.
			{#if largestVaults.length}
				The largest {largestVaults.length === 1 ? 'vault is' : 'vaults are'}
				{#each largestVaults as vault, index (vault.vault_slug)}{index > 0 ? ', ' : ''}<a
						href={resolveVaultDetails(vault)}>{vault.name}</a
					>{/each}{#if topProtocols.length}
					{' '}
					and the most popular vault {topProtocols.length === 1 ? 'protocol is' : 'protocols are'}
					{#each topProtocols as protocol, index (protocol.slug)}{index === 0
							? ''
							: index === topProtocols.length - 1
								? ' and '
								: ', '}<a href={resolve(`/trading-view/vaults/protocols/${protocol.slug}`)}>{protocol.name}</a
						>{/each}{/if}.
			{/if}
			{#if averageYieldLabel}
				The last 30 days' average yield is <strong>{averageYieldLabel}</strong>.
			{/if}
		</p>
		{#if excludedVaultCount > 0}
			<p>
				{excludedVaultCount}
				{excludedVaultCount === 1 ? 'vault is' : 'vaults are'} excluded from this ranking due to minimum TVL requirements
				or risk issues.
			</p>
		{/if}
	</MetricsBox>
</div>

<style>
	.vault-group-description {
		display: contents;
		font: var(--f-ui-md-roman);
		color: var(--c-text-light);

		p {
			margin: 0;
			line-height: 1.5;

			& + p {
				margin-top: 0.75rem;
			}
		}

		strong {
			color: var(--c-text);
			font-weight: 600;
		}

		a {
			color: var(--c-text);
			text-decoration: underline;
			text-underline-offset: 0.2em;
		}
	}
</style>
